/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { ERC2981, ERC2981Interface } from "../ERC2981";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "salePrice",
        type: "uint256",
      },
    ],
    name: "royaltyInfo",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes4",
        name: "interfaceId",
        type: "bytes4",
      },
    ],
    name: "supportsInterface",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5060408051808201909152338082526103e8602090920191909152607d60a31b17600055610250806100436000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c806301ffc9a71461003b5780632a55205a14610063575b600080fd5b61004e610049366004610178565b610095565b60405190151581526020015b60405180910390f35b6100766100713660046101a9565b6100cc565b604080516001600160a01b03909316835260208301919091520161005a565b60006001600160e01b0319821663152a902d60e11b14806100c657506301ffc9a760e01b6001600160e01b03198316145b92915050565b60008281526001602090815260408083208151808301909252546001600160a01b038116808352600160a01b9091046001600160601b03169282019290925282916101415750604080518082019091526000546001600160a01b0381168252600160a01b90046001600160601b031660208201525b602081015160009061271090610160906001600160601b0316876101cb565b61016a91906101f8565b915196919550909350505050565b60006020828403121561018a57600080fd5b81356001600160e01b0319811681146101a257600080fd5b9392505050565b600080604083850312156101bc57600080fd5b50508035926020909101359150565b60008160001904831182151516156101f357634e487b7160e01b600052601160045260246000fd5b500290565b60008261021557634e487b7160e01b600052601260045260246000fd5b50049056fea2646970667358221220fe32c87ab44b64d37719e911fd60b3bd3a0399c2d1d710daa501394c2b61348564736f6c63430008090033";

export class ERC2981__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ERC2981> {
    return super.deploy(overrides || {}) as Promise<ERC2981>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): ERC2981 {
    return super.attach(address) as ERC2981;
  }
  connect(signer: Signer): ERC2981__factory {
    return super.connect(signer) as ERC2981__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ERC2981Interface {
    return new utils.Interface(_abi) as ERC2981Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ERC2981 {
    return new Contract(address, _abi, signerOrProvider) as ERC2981;
  }
}
